name: Slipdisk
version: ${project.version}
main: com.belinski20.slipdisk.Slipdisk
api-version: 1.15
authors: [belinski20]
description: A SpinalCraft exclusive plugin for a close to vanilla teleportation system
depend: [Vault]

commands:
  slip:
    permission-message: Do not have valid permissions to use
    description: Gives Description of what slipdisk is
    permission: slipdisk.slip
  update:
    permission-message: Do not have valid permissions to use
    description: Goes through each player's file and updates ranks and slip totals from permissions
    permission: slipdisk.update