name: Slipdisc
version: ${project.version}
main: com.slipdisc.slipdisc.Slipdisc
api-version: 1.13
authors: [Belinski20]
description: Teleport Plugin to feel more like Vanilla

commands:
  slipdisc:
    permission-message: Do not have valid permissions to use
    description: Vanilla Teleport Plugin
    permission: slipdisc.access