name: Slipdisk
version: ${project.version}
main: com.belinski20.slipdisk.Slipdisk
api-version: 1.13
authors: [belinski20]
description: Close to vanilla teleport plugin

commands:
  slipdisk:
    permission-message: Do not have valid permissions to use
    description: Gives Description of what slipdisk is
    permission: slipdisk.slipdisk